database:
  host: postgres  # Имя сервиса из docker-compose
  port: 5432
  user: restaurant_user
  password: restaurant_pass
  database: restaurant_db

rabbitmq:
  host: rabbitmq  # Имя сервиса из docker-compose
  port: 5672
  user: guest
  password: guest